### ISSUE TITLE
Add support for relative?

### ISSUE THREAD

**Issue by walro** [twingly/twingly-url#100]
I think we could expose [addressable's relative](http://www.rubydoc.info/gems/addressable/Addressable/URI#relative%3F-instance_method). We use it in Remora. I think it would be nice if Remora could stop depending (directly) upon Addressable and use twingly-url instead.

**Comment by dentarg** [comment]
I'm not sure how we would do it, we sort out almost all bad (invalid) URLs by looking at the scheme and the hostname.

Do you have an idea how to make this work?

**Comment by walro** [comment]
True, didn't think of the public suffix step. This would basically be a static false for non nullurls :)

**Comment by walro** [comment]
Maybe an optional parameter to parse which allows for relative URLs, but I can imagine that will get messy.

**Comment by dentarg** [comment]
Yeah, it will get messy, I have a hard time seeing how it could be combined with parsing full URLs. Not sure we need it at all... see https://github.com/twingly/remora/issues/77#issuecomment-250303836

Also, I was curious, this is how Addressable implement `relative?`:

```ruby
def relative?
  return self.scheme.nil?
end
```

Also did some tests

```ruby
pry(main)> Addressable::URI.parse('hej').relative?
=> true
Addressable::URI.heuristic_parse('hej').relative?
=> true

Addressable::URI.parse('hej.com').relative?
=> true
pry(main)> Addressable::URI.heuristic_parse('hej.com').relative?
=> false
```

**Comment by walro** [comment]
Agreed, lets close.
