### ISSUE TITLE
Release a new version (without idn-ruby)

### ISSUE THREAD

**Issue by jage** [twingly/twingly-url#110]
Lots of good work that's not released: https://github.com/twingly/twingly-url/compare/v5.0.1...master

**Comment by roback** [comment]
Im unsure on which version to bump. I think the fact that we now support JRuby should count as a minor release at least.

**Comment by jage** [comment]
> Im unsure on which version to bump. I think the fact that we now support JRuby should count as a minor release at least.

I'm thinking minor as well.

The only spec changes are regarding an bug (patch) https://github.com/twingly/twingly-url/compare/v5.0.1...master#diff-9cc625410830734f3ecfe98392f89acd so I nothing should "break".

**Comment by dentarg** [comment]
Sure, 5.1.0 sounds good to me too.

**Comment by roback** [comment]
`5.1.0` it is then :)
