### ISSUE TITLE
Discrepancy with .NET normalization

### ISSUE THREAD

**Issue by walro** [twingly/twingly-url#12]
Using url: `http://www.blog.com/feed/` the normalizer returns `http://www.blog.com/feed/` while the .NET based normalization would return `http://www.blog.com/feed`. So this library is not safe to use in conjunction with .NET based projects, such as Autoping.

The .NET filtering is done in: `\trunk\Utilities\Filtering\UrlFilter.cs`

In: `\trunk\Utilities\Filter.Test\TestUrlFilter.cs` there are lots of tests defining the behavior (Including tests for stripping trailing slash in path).

**Comment by roback** [comment]
This is needed to test whether a url is added to autoping, as im trying to do in https://trello.com/c/KG5vNOEA/1286-sommar2015-verktyg-for-att-jobba-med-url-listor

**Comment by jage** [comment]
We discussed this on the sprint meeting for [sprint 32](https://trello.com/c/v1BCxbyH/1355-sprint32-planering-och-uppfoljning) and decided that this isn't critical. We would very much like this, but it won't be prioritized now.
