### ISSUE TITLE
Remove www. for domains with "subdomains"

### ISSUE THREAD

**Issue by jage** [twingly/twingly-url#18]
`http://www.blog.twingly.com/` should be normalized to `http://blog.twingly.com/` according to ` /trunk/Utilities/Filtering/UrlFilter.cs` and `/trunk/Utilities/Filter.Test/TestUrlFilter.cs`.

**Comment by roback** [comment]
We can't reproduce this. Proof in: http://systemutil.live.lkp.primelabs.se/documentdb/8155421525997345110 link still has www before subdomain.

Post: https://twfakeblog.herokuapp.com/urls/uris/2015/09/08/moar-url-test.html

**Comment by jage** [comment]
:+1: 

Might have been fooled by WordPress that does http://www.blog.twingly.com/ -> http://blog.twingly.com/

```
$ http http://www.blog.twingly.com/
HTTP/1.1 301 Moved Permanently
Location: http://blog.twingly.com/
```
