### ISSUE TITLE
Automate rubygems release with Travis-CI

### ISSUE THREAD

**Issue by jage** [twingly/twingly-url#24]
Let Travis-CI release the gem when tagging: http://docs.travis-ci.com/user/deployment/rubygems/

Update all depending Twingly projects Gemfile's when it's done.

Same as https://github.com/twingly/capistrano-twingly/issues/24, https://github.com/twingly/rack-indicium/issues/10, https://github.com/twingly/twingly-analytics-api-ruby/issues/10.

**Comment by dentarg** [comment]
https://github.com/svenfuchs/gem-release might be useful

**Comment by dentarg** [comment]
We tried to do this but gave up at https://github.com/twingly/twingly-search-api-ruby#10

I don't think we need to do this, we have another process now, see https://github.com/twingly/twingly-search-api-ruby#development-and-release (we currently do the same for this repo, but the instructions here are much more brief) that both tags and uploads to rubygems.org, so I don't think this will help that much (or at all).

**Comment by dentarg** [comment]
Improve the instructions in https://github.com/twingly/twingly-url/commit/3f7a20adb49250e091da28e1bcc2ad859b6cf31e.
