### ISSUE TITLE
normalize method can't handle URLs with punycoded TLD

### ISSUE THREAD

**Issue by walro** [twingly/twingly-url#28]
```ruby
[12] pry(main)> Twingly::URL::Normalizer.normalize("http://xn--80aesdcplhhhb0k.xn--p1ai/")
=> []
```

Page loads fine in Chrome though, whois works fine too.

**Comment by walro** [comment]
It was pointed out that the TLD is really funky here.

**Comment by dentarg** [comment]
Strange, xn--p1ai is in [the public suffix list](https://github.com/weppos/publicsuffix-ruby/blob/1c452b92902d02c75dbc8ed4a8630ab94e461ad2/data/definitions.txt#L6741-L6743)

I tested too, with public_suffix 1.5.1, got the same as above.

Don't really know of public_suffix work, if that above should be enough to support xn--p1ai or if they are missing something. 

Could it an encoding issue?

**Comment by walro** [comment]
> Could it be an encoding issue?

Yeah, to get it working (with public-suffix) we need to go from punycode back to utf-8:

```ruby
irb(main):005:0> PublicSuffix.valid?("xn--80aesdcplhhhb0k.xn--p1ai")
=> false
irb(main):006:0> PublicSuffix.valid?("domain.рф")
=> true
```

Public suffix won't add support for it: https://github.com/weppos/publicsuffix-ruby/issues/24

We could use https://github.com/mmriis/simpleidn (I found other, even less maintained, alternatives too) to do this ourselves.

**Comment by jage** [comment]
We should analyze our data and how many punycode TLDs do we have.
