### ISSUE TITLE
Method to extract URLs from text without normalizing

### ISSUE THREAD

**Issue by jage** [twingly/twingly-url#34]
Currently we have `Twingly::URL::Normalizer.normalize()` which can extract URLs, but it will normalize the URLs at the same time. We need a method that can just extract URLs from text with no normalization.

**Comment by dentarg** [comment]
Me and @jage talked some about this issue, from another issue:

> Uhm, to just add it, not hard. To not create a mess, pretty hard. We already have an `extract_url` method in the normalizer. So this should be in the url class, which now returns an object with a `.url` accessor ... it should probably just delegate everything except `.domain` etc ...

@jage suggested we could try some mob programming refactoring twingly-url, WDYT @walro @roback?

**Comment by roback** [comment]
:+1: That would be a good idea.

**Comment by walro** [comment]
Sure
