### ISSUE TITLE
Ensure proper behaviour for edge-case input data

### ISSUE THREAD

**Issue by twingly-mob** [twingly/twingly-url#45]
Ensure we handle the following input data like we do in .NET

* Whitespaces
* Newlines
* Garbage
* Non-URL

**Comment by twingly-mob** [comment]
We think that 57215b8ff16ad9bd19cd4eec6b320e165a39cf1e is enough.

Garbage and non-url, isn't that the same? Should we define more cases?

**Comment by jage** [comment]
> Garbage and non-url, isn't that the same?

Yes, agree. Would it be possible to create some strings with different encodings (preferably with conflicting contents) and make sure we handle them?

**Comment by twingly-mob** [comment]
> Yes, agree. Would it be possible to create some strings with different encodings (preferably with conflicting contents) and make sure we handle them?

Good idea! We'll get on it

**Comment by twingly-mob** [comment]
```C#
new System.Uri("http://abc.se/a\u3042\x81b").ToString()
"http://abc.se/aあࠛ"
```

**Comment by walro** [comment]
Seems like .NET tries to make the best of the hexvalue "0x81b" (2075 decimal) where Ruby gives up at 0x81 and leaves the b as-is.

**Comment by walro** [comment]
Ah... .NET works with UTF-16 while Ruby is UTF-8?

**Comment by dentarg** [comment]
Oh this sounds fun...

**Comment by walro** [comment]
Don't know what to do, 100% sync sounds really cumbersome... I am happy as long as twingly-url doesn't blow up, as it does now. We could go this way then:

```diff
diff --git a/lib/twingly/url.rb b/lib/twingly/url.rb
index 6d80e4b..96afab1 100644
--- a/lib/twingly/url.rb
+++ b/lib/twingly/url.rb
@@ -16,6 +16,7 @@ module Twingly
     def self.parse(potential_url)
       potential_url = String(potential_url)
       potential_url = potential_url.strip
+      potential_url = potential_url.scrub
 
       internal_parse(potential_url)
     rescue Twingly::URL::Error, Twingly::URL::Error::ParseError => error
diff --git a/spec/lib/twingly/url_spec.rb b/spec/lib/twingly/url_spec.rb
index fc00fb6..fc3dd39 100644
--- a/spec/lib/twingly/url_spec.rb
+++ b/spec/lib/twingly/url_spec.rb
@@ -30,6 +30,7 @@ def valid_urls
     "hTTP://blog.twingly.com/",
     "https://blog.twingly.com",
     "http://3.bp.blogspot.com/_lRbEHeizXlQ/Sf4RdEqCqhI/AAAAAAAAAAw/Pl8nGPsyhXc/s1600-h/images[4].jpg",
+    "http://abc.se/a\u3042\x81b",
   ]
 end
 ```

As an alternative to scrub I've seen: `str.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')` :)

**Comment by dentarg** [comment]
> Don't know what to do, 100% sync sounds really cumbersome... I am happy as long as twingly-url doesn't blow up, as it does now

Me too... I hope the number of URLs in the wild with binary data is few

> We should probably make an explicit test for bad encodings though, rather than stuffing it into the valid_urls collection

Yes, or...

**Comment by dentarg** [comment]
What about this test? Expect that we `to_s` is the same as the input (for valid URLs)

```diff
$ git d
diff --git a/spec/lib/twingly/url_spec.rb b/spec/lib/twingly/url_spec.rb
index 86ac104..5368d43 100644
--- a/spec/lib/twingly/url_spec.rb
+++ b/spec/lib/twingly/url_spec.rb
@@ -30,6 +30,7 @@ def valid_urls
     "hTTP://blog.twingly.com/",
     "https://blog.twingly.com",
     "http://3.bp.blogspot.com/_lRbEHeizXlQ/Sf4RdEqCqhI/AAAAAAAAAAw/Pl8nGPsyhXc/s1600-h/images[4].jpg",
+    "http://abc.se/aあ<U+081B>",
   ]
 end

@@ -44,6 +45,12 @@ describe Twingly::URL do

     it { is_expected.to be_a(Twingly::URL) }

+    valid_urls.each do |valid_url|
+      it "returns the valid url '#{valid_url}'" do
+        expect(described_class.parse(valid_url).to_s).to eq(valid_url)
+      end
+    end
+
     context "when given bad input" do
       let(:invalid_url) { "banan" }
```

**Comment by dentarg** [comment]
Funny that the last `'` doesn't always show

```
  .parse
    should be a kind of Twingly::URL
    returns the valid url 'hTTP://blog.twingly.com/'
    returns the valid url 'http://3.bp.blogspot.com/_lRbEHeizXlQ/Sf4RdEqCqhI/AAAAAAAAAAw/Pl8nGPsyhXc/s1600-h/images[4].jpg'
    returns the valid url 'https://blog.twingly.com'
    returns the valid url 'http://abc.se/aあࠛ'
    returns the valid url 'http://blog.twingly.com/'
```

![image](https://cloud.githubusercontent.com/assets/42626/10573313/1a8e02d0-764f-11e5-9e9d-633d1f2d159e.png)

![image](https://cloud.githubusercontent.com/assets/42626/10573293/08e0cb3a-764f-11e5-8833-d6f46d525622.png)

shows when editing the markdown of this comment:

![image](https://cloud.githubusercontent.com/assets/42626/10573302/10fe4112-764f-11e5-9d62-97e84b284e9e.png)

**Comment by walro** [comment]
> What about this test? Expect that to_s is the same as the input (for valid URLs)

I don't really understand how it tests that we can handle bad encodings, you changed the test url to something valid, no? :)

**Comment by dentarg** [comment]
Ah yes, that was me being curious

**Comment by walro** [comment]
@dentarg i modified your suggestion slightly (I wanted a context :) ), but I am not sure it's klockrent

```diff
diff --git a/spec/lib/twingly/url_spec.rb b/spec/lib/twingly/url_spec.rb
index 86ac104..41b7c63 100644
--- a/spec/lib/twingly/url_spec.rb
+++ b/spec/lib/twingly/url_spec.rb
@@ -44,6 +44,14 @@ describe Twingly::URL do
 
     it { is_expected.to be_a(Twingly::URL) }
 
+    context "when given valid urls" do
+      valid_urls.each do |valid_url|
+        it "does not modify the valid_url '#{valid_url}'" do
+          expect(described_class.parse(valid_url).to_s).to eq(valid_url)
+        end
+      end
+    end
+
     context "when given bad input" do
       let(:invalid_url) { "banan" }
```

**Comment by dentarg** [comment]
@walro yeah I feel ya... "modify" might not be the best of words for what we mean... maybe one of these: destroy, mess up, ruin, demolish

I think I like "ruin"
