### ISSUE TITLE
Store exceptions

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-url#49]
I think it could be a good idea to store the exceptions that Twingly::URL swallow. It might be useful to know why a particular wasn't valid, as the list of exceptions we rescue will [likely grow](https://github.com/twingly/twingly-url/issues/48).

We could expose `.exceptions`, just like MetaInspector does: https://github.com/jaimeiniesta/metainspector#exception-handling (we already have the `ok?` equivalent in `valid?`)

WDYT @twingly/dev?

Somewhat related to #44, #31, #25

**Comment by jage** [comment]
Sure, this would be a very good feature to have if/when we capture all unhandled exceptions. #31 should probably be solved before or at the same time as this.

**Comment by dentarg** [comment]
Just want to note that MetaInspector might remove their exception log: https://github.com/jaimeiniesta/metainspector/issues/154

**Comment by dentarg** [comment]
I don't think this is worth the effort. Close as wontfix?

**Comment by walro** [comment]
Works for me.
