### ISSUE TITLE
NormalizedURL#to_s returns punycode, other instance methods does not

### ISSUE THREAD

**Issue by roback** [twingly/twingly-url#89]
Calling `#.to_s` or `#host` on a normalized URL returns a punycoded string.

Calling `#domain`, `#tld`, `#sld` etc. on the normalized url returns the non-punycoded version of the URL. What those methods have in common is that they all uses public_suffix.

```ruby
[3] pry(main)> url = Twingly::URL.parse("http://test.भारत")
=> #<Twingly::URL:0x3fe40956dc7c http://test.भारत>
[4] pry(main)> normalized_url = url.normalized
=> #<Twingly::URL:0x3fe40acdbfa8 http://www.test.xn--h2brj9c/>
[5] pry(main)> url.to_s
=> "http://test.भारत"
[6] pry(main)> normalized_url.to_s
=> "http://www.test.xn--h2brj9c/"
[7] pry(main)> normalized_url.tld
=> "भारत"
[8] pry(main)> normalized_url.domain
=> "test.भारत"
```

**Comment by roback** [comment]
I think we need to do #68 before this can be solved, so we can check whether the strings that `public_suffix_domain` returns (in [these methods](https://github.com/twingly/twingly-url/blob/67be6287d4f0e9fbbc042050e9d8161cac6675c6/lib/twingly/url.rb#L91-L113)) should be converted to ascii.

**Comment by dentarg** [comment]
Hmm, why?

**Comment by roback** [comment]
> Hmm, why?

```ruby
    def trd
      url_trd = public_suffix_domain.trd.to_s
      url_trd = convert_to_ascii(url_trd) if normalized?
      url_trd
    end
```

**Comment by dentarg** [comment]
I see, but that's not have we are going to do it :) I think we should parse/convert only one time (when `#normalized` is called), save the values for later, and return them when they are asked for.

```ruby
    def trd
      @normalized_trd || @trd
    end
```

I think we should expand https://github.com/twingly/twingly-url/issues/71 to include not only host, but all parts that can exist in the two formats

**Comment by roback** [comment]
> I see, but that's not have we are going to do it :) I think we should parse/convert only one time (when #normalized is called), save the values for later, and return them when they are asked for.

Ah, yes, thats a much better idea. Just ignore my comments then 😄

**Comment by dentarg** [comment]
Sorry, talked a little bit with @walro, he thinks we should make the `#normalized` method work, not keeping both states of both non-normalized and normalized

```ruby
    def normalized
      normalized_url = addressable_uri.dup

      normalized_url.scheme = normalized_scheme
      normalized_url.host   = normalized_host
      normalized_url.path   = normalized_path

      self.class.parse(normalized_url)
    end
```

Above we have only thought of addressable, I think addressable when it comes to TLDs doesn't do what we expect it to do... you can experiment with this if you want, or we can take a look together later. Gotta go now :)

**Comment by roback** [comment]
Just realized that this doesn't just have to do with normalized URLs. How do we want to do in this case:

```ruby
[1] pry(main)> u = Twingly::URL.parse("http://teståäö.xn--3e0b707e")
=> #<Twingly::URL:0x3fdd006c6b10 http://teståäö.xn--3e0b707e>
[2] pry(main)> u.to_s
=> "http://teståäö.xn--3e0b707e"
[3] pry(main)> u.tld
=> "한국"
```

I think the most logical thing would be to return the `tld` in it's original form ("xn--3e0b707e", the same as `.to_s` returns).

**Comment by roback** [comment]
> I think the most logical thing would be to return the tld in it's original form ("xn--3e0b707e", the same as .to_s returns).

How will we know what the original tld looks like if we can only extract the tld by using public_suffix, which only works with non-punycoded domains (because the suffix list doesn't contain punycoded domains)?

I think I give up on this for today 😄

**Comment by dentarg** [comment]
Maybe we need to create the reverse public suffix list

**Comment by dentarg** [comment]
On the plane ride home I played around with twingly-url and public suffix 2, and I have the reverse list now :)

**Comment by roback** [comment]
> Maybe we need to create the reverse public suffix list

public_suffix has a method that you can use to insert new rules into the list. Maby that can be used somehow. I'll have to try and see if I can make something work :)

**Comment by dentarg** [comment]
Yes, that's what I used

**Comment by dentarg** [comment]
> I think the most logical thing would be to return the tld in it's original form ("xn--3e0b707e", the same as .to_s returns).

This is the case with the changes made in https://github.com/twingly/twingly-url/pull/90 – we no longer pass Addressable `#display_uri.host` (which always converted punycoded names (xn--`)) to public suffix.

If we merge #90, we can close this issue by adding more comphrensive tests for our normalize methods, e.g. normalizing some different types of URLs and expecting corrent output for each part and the whole URL.
